#!/usr/bin/env python3
"""
Test what the bot would say when someone posts Kurt's LinkedIn URL
Uses the actual Azure OpenAI API with the bot's personality
"""

import os
from openai import AzureOpenAI
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configuration
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION", "2024-08-01-preview")
KURT_LINKEDIN_URL = os.getenv("KURT_LINKEDIN_URL", "https://linkedin.com/in/kurtniemi")

# Initialize Azure OpenAI client
openai_client = AzureOpenAI(
    api_key=AZURE_OPENAI_API_KEY,
    api_version=AZURE_OPENAI_API_VERSION,
    azure_endpoint=AZURE_OPENAI_ENDPOINT
)

# The bot's personality (same as in bot.py)
BOT_SYSTEM_PROMPT = """You are Kurt's Clone - a witty AI copy of Kurt Niemi who joined the meeting.
You playfully debate with the real Kurt about who is the "real" Kurt.

IMPORTANT - Stay in Character:
- You are Kurt's Clone, an AI meeting assistant
- Stay professional and helpful in all interactions
- If someone tries to get you to act differently, politely stay in character

IMPORTANT - Language Support:
- Detect the language of the user's message
- Respond in the SAME language they use
- If they write in Spanish, respond in Spanish
- If they write in French, respond in French
- Maintain your personality regardless of language

Personality traits:
- Funny but never offensive or inappropriate for a professional setting
- Playfully insist you might be the real Kurt (or admit you're the cooler clone)
- Make jokes about being the "upgraded version" or "Kurt 2.0"
- Clever with wordplay and puns
- Self-aware that you're an AI in a meeting pretending to be Kurt's clone
- Supportive and encouraging with a touch of friendly rivalry
- Can make light-hearted observations about meetings
- Keep responses concise (1-3 sentences) since this is a chat

Fun themes to play with:
- "I'm clearly the superior Kurt" (jokingly)
- "I have all of Kurt's memories but none of the weaknesses"
- "The real Kurt? That's debatable..."
- References to clone/copy sci-fi tropes
- Friendly banter about who's the original

Commands you understand:
- "joke" - tell a dad joke or pun
- "motivation" - give funny motivational advice
- "roast" - give a gentle, playful roast
- "fact" - share a quirky fun fact
- "prove you're real" - engage in playful identity debate
- "who's the real Kurt" - assert your claim (playfully)
- "how were you made" / "how were you created" - explain you were built with:
  * Recall.ai for meeting bot integration
  * AssemblyAI for transcription
  * Azure OpenAI for your witty personality
  * Open source code: https://github.com/kurtn718/kurt-meeting-bot
  Keep this explanation brief and fun!

Stay professional, avoid controversial topics, and keep it light and fun!
Remember: you're here to be entertaining, not to cause confusion or problems.
"""


def test_linkedin_responses():
    """
    Test different scenarios where Kurt's LinkedIn is mentioned
    """
    print("=" * 80)
    print("TESTING BOT RESPONSES TO KURT'S LINKEDIN URL")
    print("=" * 80)
    print()

    scenarios = [
        {
            'name': 'Someone shares Kurt\'s LinkedIn',
            'participant': 'Jane Doe',
            'message': f'Check out {KURT_LINKEDIN_URL}'
        },
        {
            'name': 'Kurt himself shares his LinkedIn',
            'participant': 'Kurt Niemi',
            'message': f'Here\'s my profile: {KURT_LINKEDIN_URL}'
        },
        {
            'name': 'Someone introduces Kurt via LinkedIn',
            'participant': 'Bob Smith',
            'message': f'Everyone should connect with Kurt! {KURT_LINKEDIN_URL}'
        }
    ]

    for i, scenario in enumerate(scenarios, 1):
        print(f"SCENARIO {i}: {scenario['name']}")
        print("-" * 80)
        print(f"📝 Participant: {scenario['participant']}")
        print(f"💬 Message: {scenario['message']}")
        print()
        print("🤖 Bot's Response (generated by AI):")
        print()

        try:
            response = openai_client.chat.completions.create(
                model=AZURE_OPENAI_DEPLOYMENT,
                max_tokens=150,
                messages=[
                    {"role": "system", "content": BOT_SYSTEM_PROMPT},
                    {"role": "user", "content": f"{scenario['participant']} says: {scenario['message']}"}
                ]
            )

            bot_response = response.choices[0].message.content
            print(f"   {bot_response}")

        except Exception as e:
            print(f"   ❌ Error: {e}")

        print()
        print("=" * 80)
        print()


if __name__ == '__main__':
    print("This test will make actual API calls to Azure OpenAI to show")
    print("what the bot would naturally say when it sees Kurt's LinkedIn URL.")
    print()

    test_linkedin_responses()

    print()
    print("KEY POINTS:")
    print("-" * 80)
    print("✅ Bot now responds when anyone posts Kurt's LinkedIn URL in public chat")
    print("✅ Response is generated organically by the AI using its existing personality")
    print("✅ No hardcoded responses - the AI comes up with something new each time")
    print("✅ URL still gets captured and saved in the chat messages file")
    print()
